<a href="https://colab.research.google.com/github/Yovana-Palencia/CPU_8bits/blob/main/Miner%C3%ADa_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de datos

##Primer parcial

###Introducción

####Conceptos

¿Qué es minería de datos?
Es una técnica asistida por computadora que se utiliza en los análisis para procesar y explorar grandes conjuntos de datos

###Ciencia de datos

¿Qué es ciencia de datos? Es el estudio de datos con el fin de extraer información significativa para empresas.

####Help and Documentation in IPython

In [ ]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
#Otra forma de obtener ayuda es utilizando ?
len?

In [ ]:
#Ejemplo de ayuda en una lista
L=[1,2,3]
L.insert?

In [ ]:
L?

In [ ]:
#Ejemplo con una función
def square(a):
  """Return the square of a."""
  return a ** 2

In [ ]:
square?

In [ ]:
square??

In [ ]:
#La función help nos muestra la ayuda
help(square)

Help on function square in module __main__:

square(a)
    Return the square of a.



In [ ]:
L.insert

####Help on magic functions:?, %magic, and %Ismagic

In [2]:
%timeit?

In [1]:
%magic

In [4]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %shell  %store  %sx  %system  %tb  %tensorflow_version  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%bigquery  %%bqsql  %%capture  %%debug  %%file  %%html  %%javascript  %%j

####IPython and Shell Commands

In [8]:
$ echo "hello world"

SyntaxError: invalid syntax (ipython-input-3926258238.py, line 1)

####Understanding data types in Python

In [9]:
import numpy as np

In [10]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [11]:
np.array([3.14, 4. , 2. , 3. ])

array([3.14, 4.  , 2.  , 3.  ])

In [12]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [13]:
np.array([1,2,3,4], dtype='int')

array([1, 2, 3, 4])

In [14]:
np.array([range(i,i + 3)for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])