<a href="https://colab.research.google.com/github/Yovana-Palencia/CPU_8bits/blob/main/Miner%C3%ADa_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de datos

##Primer parcial

###Introducción

####Conceptos

¿Qué es minería de datos?
Es una técnica asistida por computadora que se utiliza en los análisis para procesar y explorar grandes conjuntos de datos

###Ciencia de datos

¿Qué es ciencia de datos? Es el estudio de datos con el fin de extraer información significativa para empresas.

####Help and Documentation in IPython

In [ ]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
#Otra forma de obtener ayuda es utilizando ?
len?

In [ ]:
#Ejemplo de ayuda en una lista
L=[1,2,3]
L.insert?

In [ ]:
L?

In [ ]:
#Ejemplo con una función
def square(a):
  """Return the square of a."""
  return a ** 2

In [ ]:
square?

In [ ]:
square??

In [ ]:
#La función help nos muestra la ayuda
help(square)

Help on function square in module __main__:

square(a)
    Return the square of a.



In [ ]:
L.insert

####Help on magic functions:?, %magic, and %Ismagic

In [ ]:
%timeit?

In [ ]:
%magic

In [ ]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %shell  %store  %sx  %system  %tb  %tensorflow_version  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%bigquery  %%bqsql  %%capture  %%debug  %%file  %%html  %%javascript  %%j

####IPython and Shell Commands

In [ ]:
$ echo "hello world"

SyntaxError: invalid syntax (ipython-input-3926258238.py, line 1)

####Understanding data types in Python

In [ ]:
import numpy as np

In [ ]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [ ]:
np.array([3.14, 4. , 2. , 3. ])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1,2,3,4], dtype='int')

array([1, 2, 3, 4])

In [ ]:
np.array([range(i,i + 3)for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [1]:
import numpy as np

In [2]:
np.random.seed(0) #seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [3]:
print("x3 ndim: ", x3.ndim)  # La propiedad ndim nos dice el número de dimesniones
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [4]:
print(x2.dtype)  # dtype nos dice el tipo de datos

int64


In [5]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [6]:
x1

array([5, 0, 3, 3, 7, 9])

In [7]:
x1[0]  # Colocamos el índice del elemento a extraer, en este caso el primer elemento tienen el ídice 0

np.int64(5)

In [8]:
x1[4]

np.int64(7)

In [9]:
x1[-1]  # Nos regresa el último elemento del ndarray

np.int64(9)

In [10]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [11]:
x2[0, 0]

np.int64(3)

In [12]:
x2[0, 2]

np.int64(2)

In [13]:
x2[0, 0] = 12  # Asignar un nuevo valor (12) al renglón 0 columna 0
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])